### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Stef3478** [gettyimages/marathon_exporter#2]
Hi,

When I run the marathon_exporter I get a runtime error. I get this with every possible argument combination I tried. 
I tried both compiling the application myself and using go itself to install it.

Any ideas what could be going on?

Thanks

 ./marathon_exporter  -marathon.uri "http://10.231.158.6:8080" -web.telemetry-path "/metrics"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x408467]

goroutine 1 [running]:
panic(0x84fb40, 0xc820010100)
        /home/user/go/src/runtime/panic.go:464 +0x3e6
main.marathonConnect(0xc820074480, 0x0, 0x0)
        /home/user/tmp/marathon_exporter/main.go:33 +0xe7
main.main()
        /home/usertmp/marathon_exporter/main.go:73 +0x15e

**Comment by dylanmei** [comment]
Thanks for your issue! Commit 0e1c659d93155c02e1337c4ac7b6d81b5044d722 should make this go away.

**Comment by Stef3478** [comment]
It works now, thanks!!
