### ISSUE TITLE
Looking for maintainer(s)

### ISSUE THREAD

**Issue by mapitman** [gettyimages/marathon_exporter#22]
We're looking for maintainers. We'd like to transfer this project to someone who wants to carry it forward. Please reply to this issue if you are interested.

**Comment by kamaradclimber** [comment]
@mapitman I would be interested in maintaining this repository. I'll probably maintain it as part of my day job (criteo) since we heavily use marathon.
How could transfer work?

**Comment by mapitman** [comment]
I believe I can transfer it to your account (but not to an organization I don't have rights to). Then you could transfer it you your criteo org if that's what you want to do.

**Comment by kamaradclimber** [comment]
Good idea. Thanks

Le jeu. 1 nov. 2018 à 16:22, Mark Pitman <notifications@github.com> a
écrit :

**Comment by mapitman** [comment]
Is that what you'd like to do then?

**Comment by mapitman** [comment]
I'll just do it.

**Comment by kamaradclimber** [comment]
I have just accepted thz transfer. Will now look how to transfer to criteo
org.
Thanks a lot for your help!

Le jeu. 1 nov. 2018 à 22:20, Mark Pitman <notifications@github.com> a
écrit :
